/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect, ChangeEvent } from "react";
import { GoogleGenAI } from "@google/genai";
import { motion, AnimatePresence } from "motion/react";
import { Upload, Camera, Sparkles, Loader2, RefreshCw, ChevronRight, Image as ImageIcon } from "lucide-react";

// Initialize Gemini API
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export default function App() {
  const [image, setImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
        setResultImage(null);
        setError(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const generatePhotoshoot = async () => {
    if (!image) return;

    setIsGenerating(true);
    setError(null);

    try {
      const base64Data = image.split(",")[1];
      const mimeType = image.split(";")[0].split(":")[1];

      const prompt = "Hyper-realistic cinematic fashion photoshoot of the person in the image (height 5’5”). Seated on a deep black bean bag, he wears bold all-black oversized streetwear: black shirt, black baggy pants, airforce one white, silver watch. Solid grey background. Powerful drip vibes, Adidas campaign editorial look, dramatic studio lighting... 8k resolution quality. Keep the face in the picture 100% and ensure it looks exactly like the person in the uploaded photo.";

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Data,
                mimeType: mimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      });

      let foundImage = false;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          setResultImage(`data:${part.inlineData.mimeType};base64,${part.inlineData.data}`);
          foundImage = true;
          break;
        }
      }

      if (!foundImage) {
        throw new Error("No image was generated by the model. Please try again.");
      }
    } catch (err: any) {
      console.error("Generation error:", err);
      setError(err.message || "An error occurred during generation.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-white selection:text-black">
      {/* Header */}
      <header className="border-b border-white/10 p-6 flex justify-between items-center sticky top-0 bg-black/80 backdrop-blur-md z-50">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-white rounded-full flex items-center justify-center">
            <Camera className="text-black w-5 h-5" />
          </div>
          <h1 className="text-xl font-light tracking-widest uppercase">Drip Studio</h1>
        </div>
        <div className="text-[10px] uppercase tracking-[0.2em] text-white/40 font-medium">
          Powered by Gemini 2.5 Flash
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-12 lg:py-20">
        <div className="grid lg:grid-cols-2 gap-16 items-start">
          {/* Left Column: Controls */}
          <div className="space-y-12">
            <div className="space-y-4">
              <motion.h2 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-6xl lg:text-8xl font-light tracking-tighter leading-[0.9]"
              >
                The <span className="italic font-serif">New</span> <br /> Standard.
              </motion.h2>
              <p className="text-white/60 max-w-md text-lg font-light leading-relaxed">
                Upload your portrait and transform it into a high-end fashion editorial. 
                Cinematic lighting, oversized streetwear, and pure drip vibes.
              </p>
            </div>

            <div className="space-y-8">
              {/* Upload Area */}
              <div 
                onClick={() => fileInputRef.current?.click()}
                className={`group relative border border-dashed border-white/20 rounded-3xl p-12 transition-all cursor-pointer hover:border-white/40 hover:bg-white/5 ${image ? 'bg-white/5 border-white/40' : ''}`}
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  className="hidden" 
                  accept="image/*" 
                  onChange={handleImageUpload}
                />
                
                <div className="flex flex-col items-center text-center space-y-4">
                  {image ? (
                    <div className="relative w-32 h-32 rounded-2xl overflow-hidden shadow-2xl">
                      <img src={image} alt="Preview" className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                        <RefreshCw className="w-6 h-6" />
                      </div>
                    </div>
                  ) : (
                    <div className="w-16 h-16 bg-white/10 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform">
                      <Upload className="w-6 h-6" />
                    </div>
                  )}
                  
                  <div>
                    <p className="text-sm font-medium uppercase tracking-widest">
                      {image ? "Change Photo" : "Upload Portrait"}
                    </p>
                    <p className="text-xs text-white/40 mt-1 uppercase tracking-wider">
                      JPG, PNG or WebP
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <button
                disabled={!image || isGenerating}
                onClick={generatePhotoshoot}
                className="w-full group relative overflow-hidden bg-white text-black py-6 rounded-full font-medium uppercase tracking-[0.2em] text-sm transition-all hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:hover:scale-100"
              >
                <AnimatePresence mode="wait">
                  {isGenerating ? (
                    <motion.div 
                      key="loading"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="flex items-center justify-center gap-3"
                    >
                      <Loader2 className="w-5 h-5 animate-spin" />
                      <span>Developing...</span>
                    </motion.div>
                  ) : (
                    <motion.div 
                      key="idle"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="flex items-center justify-center gap-3"
                    >
                      <Sparkles className="w-5 h-5" />
                      <span>Generate Photoshoot</span>
                    </motion.div>
                  )}
                </AnimatePresence>
              </button>

              {error && (
                <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 text-xs uppercase tracking-wider text-center">
                  {error}
                </div>
              )}
            </div>
          </div>

          {/* Right Column: Result Display */}
          <div className="relative aspect-[3/4] w-full">
            <div className="absolute inset-0 border border-white/10 rounded-[40px] overflow-hidden bg-zinc-900/50">
              <AnimatePresence mode="wait">
                {resultImage ? (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, scale: 1.1 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="w-full h-full relative"
                  >
                    <img 
                      src={resultImage} 
                      alt="Generated Photoshoot" 
                      className="w-full h-full object-cover"
                      referrerPolicy="no-referrer"
                    />
                    <div className="absolute bottom-8 left-8 right-8 flex justify-between items-end">
                      <div className="space-y-1">
                        <p className="text-[10px] uppercase tracking-[0.3em] text-white/60">Collection</p>
                        <p className="text-2xl font-serif italic">Drip 01</p>
                      </div>
                      <button 
                        onClick={() => {
                          const link = document.createElement('a');
                          link.href = resultImage;
                          link.download = 'drip-studio-photoshoot.png';
                          link.click();
                        }}
                        className="p-4 bg-white/10 backdrop-blur-md rounded-full border border-white/20 hover:bg-white/20 transition-colors"
                      >
                        <ChevronRight className="w-6 h-6" />
                      </button>
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="placeholder"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="w-full h-full flex flex-col items-center justify-center text-white/20 space-y-6"
                  >
                    <div className="w-24 h-24 border border-white/10 rounded-full flex items-center justify-center">
                      <ImageIcon className="w-10 h-10" />
                    </div>
                    <div className="text-center space-y-2">
                      <p className="text-xs uppercase tracking-[0.4em]">Awaiting Input</p>
                      <p className="text-[10px] uppercase tracking-[0.2em] opacity-50">Your editorial will appear here</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Loading Overlay */}
              {isGenerating && (
                <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex flex-col items-center justify-center space-y-8 z-10">
                  <div className="relative">
                    <div className="w-20 h-20 border-2 border-white/10 rounded-full animate-[spin_3s_linear_infinite]"></div>
                    <div className="absolute inset-0 border-t-2 border-white rounded-full animate-spin"></div>
                  </div>
                  <div className="text-center space-y-2">
                    <p className="text-xs uppercase tracking-[0.5em] animate-pulse">Processing Image</p>
                    <p className="text-[10px] uppercase tracking-[0.2em] text-white/40">Applying cinematic lighting & streetwear</p>
                  </div>
                </div>
              )}
            </div>
            
            {/* Decorative Elements */}
            <div className="absolute -top-4 -right-4 w-24 h-24 border-t border-r border-white/20 rounded-tr-3xl pointer-events-none"></div>
            <div className="absolute -bottom-4 -left-4 w-24 h-24 border-b border-l border-white/20 rounded-bl-3xl pointer-events-none"></div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="max-w-7xl mx-auto px-6 py-12 border-t border-white/10 flex flex-col md:flex-row justify-between items-center gap-8 text-[10px] uppercase tracking-[0.2em] text-white/40">
        <div className="flex gap-8">
          <span>© 2026 Drip Studio</span>
          <span>Privacy Policy</span>
          <span>Terms of Service</span>
        </div>
        <div className="flex gap-8">
          <span>Instagram</span>
          <span>Twitter</span>
          <span>Vogue Editorial</span>
        </div>
      </footer>
    </div>
  );
}
